import { AiOutlineNumber, AiOutlineUpload } from "react-icons/ai";
import { BiVideo } from "react-icons/bi";
import {
  BsFillGeoFill,
  BsLink45Deg,
  BsQuestionLg,
  BsTable,
} from "react-icons/bs";
import { CgCalendarDates, CgViewList } from "react-icons/cg";
import {
  IoIosMusicalNotes,
  IoMdCheckboxOutline,
  IoMdRadioButtonOn,
} from "react-icons/io";
import {
  MdAccessTime,
  MdOutlineDateRange,
  MdOutlineShortText,
} from "react-icons/md";
import { RiBarcodeLine } from "react-icons/ri";
import { RxTextAlignRight } from "react-icons/rx";
import { SiLineageos } from "react-icons/si";
import { SlBadge, SlPicture } from "react-icons/sl";
import { TbHandFinger, TbStars, TbWritingSign } from "react-icons/tb";
import { TiTickOutline } from "react-icons/ti";
import { VscNotebook } from "react-icons/vsc";

const SIZE = 20;

export const inputListData = [
  {
    title: "text",
    options: [
      {
        title: "Short Text",
        value: "shorttext",
        icon: <MdOutlineShortText size={SIZE} />,
        field: {
          id: "1",
          type: "string",
          label: "Short text",
          typeLabel: "Short text",
          questionType: "shorttext",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "input",
        },
      },
      {
        title: "long text",
        value: "longText",
        icon: <RxTextAlignRight size={SIZE} />,
        field: {
          id: "2",
          type: "string",
          label: "long text",
          typeLabel: "long text",
          questionType: "longtext",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "multiline",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "textarea",
        },
      },
    ],
  },
  {
    title: "location",
    options: [
      {
        title: "geo point",
        value: "geoPoint",
        icon: <BsFillGeoFill size={SIZE} />,
        field: {
          id: "5",
          type: "geopoint",
          label: "geo point",
          typeLabel: "geo point",
          questionType: "geopoint",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "maps",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "geopoint",
        },
      },
      {
        title: "geo shape",
        value: "geoShape",
        icon: <SiLineageos size={SIZE} />,
        field: {
          id: "5.2",
          type: "geoshape",
          label: "geo shape",
          typeLabel: "geo shape",
          questionType: "geoshape",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "maps",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "geoshape",
        },
      },
    ],
  },
  {
    title: "number",
    options: [
      {
        title: "number",
        value: "number",
        icon: <AiOutlineNumber size={SIZE} />,
        field: {
          id: "2",
          type: "int",
          label: "number",
          typeLabel: "number",
          questionType: "number",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "number",
        },
      },
      {
        title: "decimal",
        value: "decimal",
        icon: <AiOutlineNumber size={SIZE} />,
        field: {
          id: "2",
          type: "decimal",
          label: "decimal",
          typeLabel: "decimal",
          questionType: "number",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "number",
        },
      },
    ],
  },
  {
    title: "date & time",
    options: [
      {
        title: "date",
        value: "date",
        icon: <MdOutlineDateRange size={SIZE} />,
        field: {
          id: "3",
          type: "date",
          label: "date",
          typeLabel: "date",
          questionType: "date",
          dateRange: null,
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "date",
        },
      },
      {
        title: "Date-time",
        value: "DateTime",
        icon: <CgCalendarDates size={SIZE} />,
        field: {
          id: "3.3",
          type: "dateTime",
          label: "Date & time",
          typeLabel: "Date & time",
          questionType: "datetime",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "Datetime",
        },
      },
      {
        title: "time",
        value: "time",
        icon: <MdAccessTime size={SIZE} />,
        field: {
          id: "3.4",
          type: "time",
          label: "time",
          typeLabel: "time",
          questionType: "time",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "time",
        },
      },
    ],
  },
  {
    title: "media",
    options: [
      {
        title: "audio",
        value: "audio",
        icon: <IoIosMusicalNotes size={SIZE} />,
        field: {
          id: "6",
          type: "binary",
          label: "audio",
          typeLabel: "audio",
          questionType: "audio",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "upload",
          preload: "",
          preloadParams: "",
          mediatype: "audio/*",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "upload-audio",
        },
      },
      {
        title: "video",
        value: "video",
        icon: <BiVideo size={SIZE} />,
        field: {
          id: "6.7",
          type: "binary",
          label: "video",
          typeLabel: "video",
          questionType: "video",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "upload",
          preload: "",
          preloadParams: "",
          mediatype: "video/*",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "upload-video",
        },
      },
      {
        title: "image",
        value: "image",
        icon: <SlPicture size={SIZE} />,
        field: {
          id: "6",
          type: "binary",
          label: "image",
          typeLabel: "image",
          questionType: "image",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "upload",
          preload: "",
          preloadParams: "",
          mediatype: "image/*",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "upload-image",
        },
      },
    ],
  },
  {
    title: "ranking & rating",
    options: [
      {
        title: "ranking",
        value: "ranking",
        icon: <SlBadge size={SIZE} />,
        field: {
          id: "1",
          type: "odk:rank",
          label: "Ranking",
          typeLabel: "Ranking",
          questionType: "ranking",
          required: false,
          readOnly: false,
          dataAttribute: "",
          hint: "Drag options to rank them.",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "odk:rank",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          // instanceId: "esdfkjdkgkedjdg",
          selectOptions: [
            {
              label: "Option 1",
              value: "1",
            },
            {
              label: "Option 2",
              value: "2",
            },
          ],
          group: false,
          groupRepeat: false,
          groupLabel: "",
          groupfields: [],
          optionType: "rank-select-one",
        },
      },
      {
        title: "rating",
        value: "rating",
        icon: <TbStars size={SIZE} />,
        field: {
          id: "2.3",
          type: "int",
          label: "rating",
          typeLabel: "rating",
          questionType: "rating",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "rating",
          style: "range",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: {
            start: "1",
            end: "5",
            step: "",
          },
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "rating",
        },
      },
    ],
  },
  {
    title: "choices",
    options: [
      {
        title: "single Select",
        value: "singleSelect",
        icon: <IoMdRadioButtonOn size={SIZE} />,
        field: {
          id: "8",
          type: "select_one",
          label: "single Select",
          typeLabel: "single Select",
          questionType: "singleselect",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "Default",
          style: "select1",
          preload: "",
          preloadParams: "",
          selectOptions: [],
          mediatype: "",
          sliderOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "select-one",
          // optionType: "dropdown",
        },
      },
      {
        title: "Multiple Select",
        value: "multipleSelect",
        icon: <IoMdCheckboxOutline size={SIZE} />,
        field: {
          id: "9",
          type: "select_multiple",
          label: "Multiple Select",
          typeLabel: "Multiple Select",
          questionType: "multipleselect",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "select",
          preload: "",
          preloadParams: "",
          selectOptions: [],
          mediatype: "",
          sliderOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "select-multiple",
        },
      },
      {
        title: "Cascading Select",
        value: "cascading_select",
        icon: <BsTable size={SIZE} />,
        field: {
          id: "4",
          type: "cascading_select",
          label: "Cascading Select",
          typeLabel: "Cascading Select",
          questionType: "cascadingselect",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: true,
          groupRepeat: false,
          groupLabel: "cascading_select",
          typeLroupLabel: "cascading_select",
          groupfields: [],
          optionType: "cascading_select",
          isCascading: true,
        },
      },
      {
        title: "Yes/No",
        value: "yesNo",
        icon: <TbHandFinger size={SIZE} />,
        field: {
          id: "8",
          type: "select1",
          label: "chooseOne",
          typeLabel: "chooseOne",
          questionType: "chooseone",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "select1",
          preload: "",
          preloadParams: "",
          selectOptions: [
            {
              label: "Yes",
              typeLabel: "Yes",

              value: "yes",
            },
            {
              label: "No",
              typeLabel: "No",

              value: "no",
            },
          ],
          mediatype: "",
          sliderOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "select-one",
        },
      },
      {
        title: "likert",
        value: "likertScale",
        icon: <CgViewList size={SIZE} />,
        field: {
          id: "8.4",
          type: "select1",
          label: "likert",
          typeLabel: "likert",
          questionType: "likert",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "likert",
          style: "select1",
          preload: "",
          preloadParams: "",
          selectOptions: [
            {
              label: "Strongly disagree",
              typeLabel: "Strongly disagree",
              value: "stronglyDisagree",
            },
            {
              label: "Disagree",
              typeLabel: "Disagree",
              value: "disagree",
            },
            {
              label: "Neutral",
              typeLabel: "Neutral",
              value: "neutral",
            },
            {
              label: "Agree",
              typeLabel: "Agree",
              value: "agree",
            },
            {
              label: "Strongly agree",
              typeLabel: "Strongly agree",
              value: "stronglyAgree",
            },
          ],
          mediatype: "",
          sliderOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "select-one",
        },
      },
      // {
      //   title: "map choices",
      //   value: "mapChoices",
      //   icon: <FiMap size={SIZE} />,
      //   field: {
      //     id: "1",
      //     type: "string",
      //     label: "map choices",
      //     typeLabel: "map choices",
      //     questionType: "map choices",
      //     required: false,
      //     meta: false,
      //     readOnly: false,
      //     dataAttribute: "",
      //     hint: "",
      //     calculate: "",
      //     constraint: "",
      //     constraintMsg: "",
      //     relevant: "",
      //     requiredMsg: "",
      //     defaultValue: "",
      //     appearance: "",
      //     style: "input",
      //     preload: "",
      //     preloadParams: "",
      //     mediatype: "",
      //     sliderOptions: null,
      //     selectOptions: null,
      //     group: false,
      //     groupRepeat: false,
      //     groupLabel: "",
      //     typeLroupLabel: "",
      //     groupfields: [],
      //   },
      // },
    ],
  },
  {
    title: "form structure",
    options: [
      {
        title: "question group",
        value: "questionGroup",
        icon: <BsQuestionLg size={SIZE} />,
        field: {
          id: "4",
          type: "",
          label: "question group",
          typeLabel: "question group",
          questionType: "group",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: true,
          groupRepeat: false,
          groupLabel: "group1",
          typeLroupLabel: "group1",
          groupfields: [],
          optionType: "group",
        },
      },
      {
        title: "Information note",
        value: "Informationnote",
        icon: <VscNotebook size={SIZE} />,
        field: {
          id: "1",
          type: "note",
          label: "note",
          typeLabel: "Information note",
          questionType: "note",
          required: false,
          meta: false,
          readOnly: true,
          dataAttribute: "note",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "none",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "note",
        },
      },
    ],
  },
  {
    title: "barcode",
    options: [
      {
        title: "barcode",
        value: "barcode",
        icon: <RiBarcodeLine size={SIZE} />,
        field: {
          id: "7",
          type: "barcode",
          label: "barcode",
          typeLabel: "barcode",
          questionType: "barcode",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "Enter barcode number here.",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "scan-barcode",
        },
      },
    ],
  },
  {
    title: "Links",
    options: [
      {
        title: "Hyperlink",
        value: "url",
        icon: <BsLink45Deg size={SIZE} />,
        field: {
          id: "1",
          type: "string",
          label: "hyperlink",
          typeLabel: "Hyperlink",
          questionType: "link",
          required: false,
          meta: false,
          readOnly: true,
          dataAttribute: "ReadonlyURL",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "https://www.google.com",
          appearance: "url",
          style: "input",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "url",
        },
      },
    ],
  },
  {
    title: "signature",
    options: [
      {
        title: "signature",
        value: "signature",
        icon: <TbWritingSign size={SIZE} />,
        field: {
          id: "6.5",
          type: "binary",
          label: "signature",
          typeLabel: "signature",
          questionType: "signature",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "Draw your signature inside the box",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "signature",
          style: "upload",
          preload: "",
          preloadParams: "",
          mediatype: "image/*",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "draw-signature",
        },
      },
    ],
  },
  {
    title: "trigger/acknowledge",
    options: [
      {
        title: "trigger",
        value: "trigger",
        icon: <TiTickOutline size={SIZE} />,
        field: {
          id: "1",
          type: "string",
          label: "trigger",
          typeLabel: "trigger",
          questionType: "trigger",
          optionType: "trigger",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "trigger",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
        },
      },
    ],
  },
  {
    title: "file upload",
    options: [
      {
        title: "file upload",
        value: "fileUpload",
        icon: <AiOutlineUpload size={SIZE} />,
        field: {
          id: "6",
          type: "binary",
          label: "file upload",
          typeLabel: "file upload",
          questionType: "fileupload",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "upload",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "upload-file",
        },
      },
    ],
  },
  {
    title: "meta questions",
    options: [
      {
        title: "background audio",
        value: "backgroundAudio",
        icon: <AiOutlineUpload size={SIZE} />,
        field: {
          id: "6",
          type: "binary",
          label: "backgroundAudio",
          typeLabel: "",
          questionType: "audio",
          required: false,
          meta: false,
          readOnly: false,
          dataAttribute: "my_recording",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          auditType: "AUDIO",
          style: "no-body",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "upload-audio",
        },
      },
      {
        title: "audit",
        value: "audit",
        icon: <AiOutlineUpload size={SIZE} />,
        field: {
          id: "7",
          type: "binary",
          label: "audit",
          typeLabel: "",
          questionType: "audit",
          required: false,
          meta: true,
          readOnly: false,
          dataAttribute: "audit",
          hint: "",
          calculate: "",
          constraint: "",
          constraintMsg: "",
          relevant: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          auditType: "TEXT",
          style: "no-body",
          preload: "",
          preloadParams: "",
          mediatype: "",
          sliderOptions: null,
          selectOptions: null,
          group: false,
          groupRepeat: false,
          groupLabel: "",
          typeLroupLabel: "",
          groupfields: [],
          optionType: "upload-audio",
        },
      },
    ],
  },
];
