apiVersion: v1
kind: Service
metadata:  
  labels:
    app: socialwell-odkformbuilder-fe
  name: socialwell-odkformbuilder-fe
spec:
  type: ClusterIP
  ports:  
    - port: 3000
      targetPort: 3000
  selector:
    app: socialwell-odkformbuilder-fe