// <text id="/data/farmer_data/fpoVillage/1:label">
//                         <value>Bhotra</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/2:label">
//                         <value>Devgav</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/3:label">
//                         <value>Dhudhi</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/4:label">
//                         <value>Donja</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/5:label">
//                         <value>Gosaviwadi</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/6:label">
//                         <value>Khasapury</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/7:label">
//                         <value>Kokarwadi</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/8:label">
//                         <value>Kumbhfal</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/9:label">
//                         <value>Lakhi</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/10:label">
//                         <value>Muggav</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/11:label">
//                         <value>Pacpimpala</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/12:label">
//                         <value>Pimparkhed</value>
//                     </text>
//                     <text id="/data/farmer_data/fpoVillage/13:label">
//                         <value>Ratnapur</value>
//                     </text>

export const villageOptions: any = {
  "WOTR-v102-Aam Jan Krushi FPC-Hindi": {
    "1": "Badla",
    "2": "Banjariya",
    "3": "Jawas",
    "4": "Jhunthri",
    "5": "Kandal",
    "6": "Karchha Kalan",
    "7": "Khanmeen",
    "8": "Parbeela",
    "9": "Pogra kalan",
    "10": "Samiter",
    "11": "Suberi",
  },
  "WOTR-v102-Aapli Agro-Marathi": {
    "1": "Bamani",
    "2": "Baramgao",
    "3": "Bembali",
    "4": "Keshegav",
    "5": "Mahadewadi",
    "6": "Patoda",
    "7": "Takviki",
    "9": "Toramba",
    "10": "Umbargaon",
    "11": "Vithalwadi",
    "12": "Wadi",
  },
  "WOTR-v102 Bamanwas-Hindi": {
    "1": "Bairada",
    "2": "Bamanwas Khurd",
    "3": "Bamanwas Patti Kalan",
    "4": "Batoda",
    "5": "Binjari",
    "6": "Chandanholi",
    "7": "Phulwara",
    "8": "Piplai",
    "9": "Shafipura",
  },
  "WOTR-v102-chawand mata FPC-Hindi": {
    "1": "Balua",
    "2": "Bandoli",
    "3": "Katanwara",
    "4": "Kejar",
    "5": "Kevri",
    "6": "Lalpura",
    "7": "Mayar",
    "8": "Sagatra",
    "9": "Chawand",
    "10": "Dingri",
    "11": "Limboda",
    "12": "Naal Halkar",
    "13": "Sarasiya",
  },
  "WOTR-v102-Idana Mata FPC-Hindi": {
    "1": "Bambora",
    "2": "Todi",
    "3": "Gudli",
    "4": "Jagat",
    "5": "Kurawar",
    "6": "Nichla Chotiya",
    "7": "Upla Chotiya",
    "8": "Parmada",
    "9": "Nar",
    "10": "Pheela",
    "11": "Ratanpura",
    "12": "Kaliwali",
    "13": "Sheeshwi",
    "14": "Sejlai",
    "15": "Bela",
    "16": "Wali",
    "17": "Sulawas",
    "18": "Rawat Pura",
    "19": "Mayda",
    "20": "Patoo khera",
  },
  "WOTR-v102-Jaisamand Kisan  FPC-Hindi": {
    "1": "Amarpura",
    "2": "Bargaon",
    "3": "Deopura",
    "4": "Jhadol",
    "5": "Kantora",
    "6": "Oda",
    "7": "Pahari",
    "8": "Peeladar",
    "9": "Relan",
    "10": "Sallara",
  },
  "WOTR-v102-Jaishri Rishabdeo FPC-Hindi": {
    "1": "Pareda",
    "2": "Garnala Kotra",
    "3": "Jaipura",
    "4": "Beechhiwara",
    "5": "Masaron Ki Ovri",
    "6": "Nichla Mandwa",
    "7": "Dhelana",
    "8": "Pandyawara",
  },
  "WOTR-v102-Jalpriya-Marathi": {
    "1": "Anandwadi",
    "2": "Antarwali",
    "3": "Bedarwadi",
    "4": "Chumbali",
    "5": "Dandegaon",
    "6": "Lonarwadi",
    "7": "Ghatnandur",
    "8": "Katewadi",
    "9": "Ida",
    "10": "Irachiwadi",
    "11": "Jamb",
    "12": "Jaywantnagar",
    "13": "Jejala",
    "14": "Malewadi",
    "15": "Nagewadi",
    "16": "Nalivadgaon",
    "17": "Nannjwadi",
    "18": "Nipani",
    "19": "Pakhrud",
    "20": "Pathrud",
    "21": "Kukkadgaon",
    "22": "Pida",
    "23": "Sawargon",
    "24": "Tintraj",
    "25": "Umachiwadi",
    "26": "Wadachiwadi",
    "27": "Walawad",
    "28": "Kokarwadi",
  },
  "WOTR-v102-Jay Bhomiya FPC-Hindi": {
    "1": "Chhan",
    "2": "Jeewli",
    "3": "Sewa",
    "4": "Toksi",
    "5": "Vinega",
  },
  "WOTR-v102-Karkela Bhairo FPC-Hindi": {
    "1": "Mahuwara",
    "2": "Karodiya",
    "3": "Sadkari Nichala Fala",
    "4": "Chandora",
    "5": "Dhan Ka Wara",
    "6": "Bori",
    "7": "Kunda",
    "8": "Jambuda Ghata",
    "9": "Sipoor",
    "10": "Lalapuriya",
  },
  "WOTR-v102-Lasadia kisanr FPC-Hindi": {
    "1": "Patiya",
    "2": "Tekan",
    "3": "Sodala",
    "4": "Berasota",
    "5": "Dholiya",
    "6": "Madawata",
    "7": "Lasadiya",
    "8": "Samel",
    "9": "Dai Ka Khera",
    "10": "Gopalpura",
  },
  "WOTR-v102-Luhakhambeswara-Odia": {
    "1": "Anagha",
    "2": "Anukampa",
    "3": "Bastriguda",
    "4": "Budisila",
    "5": "Chellagada",
    "6": "Dambadiha",
    "7": "Dumba",
    "8": "Jhada Randiba",
    "9": "Kandhadiha",
    "10": "kankadaguda",
    "11": "Katangapada",
    "12": "Khanjamera",
    "13": "Kharipada",
    "14": "Kuanpada",
    "15": "Kurtal",
    "16": "Kussapalli",
    "17": "Lubursing",
    "18": "Mahendragada",
    "19": "Patrabasa",
    "20": "R.Udayagiri",
    "21": "Ranalai",
    "22": "Sabarapalli",
    "23": "Sinisingi",
    "24": "Sundruba",
  },
  "WOTR-v102-Natural PanchKrushi-Marathi": {
    "1": "Golegaon",
    "2": "Izora",
    "3": "Jawalka",
    "4": "Lakkhangav",
    "5": "Mahaldarpuri",
    "6": "Mandva",
    "7": "Pimpalgaon (Ko)",
    "9": "Saramkundi",
    "10": "Tandulwadi",
    "11": "Washi",
  },
  "WOTR-v102-Rajerao Rambha-Marathi": {
    "1": "Jeur",
    "2": "Arjunnagar",
    "3": "Ghargaon",
    "4": "Gulsadi",
    "5": "Kem",
    "6": "Kumbhargaon",
    "7": "Kumbhej",
    "8": "Mirghavan",
    "9": "Nimbhore",
    "10": "Sarapdoh",
    "11": "Shelgaon",
    "12": "Sounde",
    "13": "Sounde",
    "14": "Taratgaon",
    "15": "Warkatne",
  },
  "WOTR-v102-Salumber Kisan  FPC-Hindi": {
    "1": "Basa",
    "2": "Saradi",
    "3": "Makarsima",
    "4": "Bassee Joyara",
    "5": "Bassee Jhujhawat",
    "6": "Bassee Samchot",
    "7": "Bassee Singawat",
    "8": "Bhai",
    "9": "Adkaliya",
    "10": "Lakapa",
    "11": "Sooron Ka Kua",
    "12": "Isarwas (Rawan)",
    "13": "Isarwas Tapran",
    "14": "Isarwas Dangiyan",
  },
  "WOTR-v102-Santadayanand-Marathi": {
    "1": "Hasnabad",
    "2": "Khadki",
    "3": "Javkheda khurd",
    "4": "Javkheda bk",
    "5": "Ekefhal",
    "6": "Kolte pimpalgaon",
    "7": "Vita",
    "9": "Nalni kh.",
    "10": "Palaskheda da.",
    "11": "Boargaon  khadak",
  },
  "WOTR-v102-Sata_Bhauni-Odia": {
    "1": "Adava",
    "2": "Amara",
    "3": "Ariba",
    "4": "Bada Gosani",
    "5": "Bada Kotturu",
    "6": "Bali Sahi",
    "7": "Chhatrapur",
    "8": "Chintapalli",
    "9": "Dalimbapur",
    "10": "Deviti",
    "11": "Gandhinagar",
    "12": "Gollagram",
    "13": "Kanchiranipeta",
    "14": "Kasimpeta",
    "15": "Kerandi",
    "16": "Kharsanda",
    "17": "Madhusudanpur",
    "18": "Naraharipur",
    "19": "Routpur",
    "20": "Sabara",
    "21": "Sadabati Laxmipur",
    "22": "Sana Kotturu",
    "23": "Sariapalli",
    "24": "Singipur",
    "25": "Soura Gosani",
    "26": "Tatipati",
    "27": "Totasahi",
    "28": "Uppalada",
    "29": "Urda",
  },
  "WOTR-v102-Shree Shambho Mahadev -Marathi": {
    "1": "Bhatagali",
    "2": "Dhanuri",
    "3": "Kasti",
    "4": "Kodjigad",
    "5": "Lohara Khu.",
    "6": "Makni",
    "7": "Mardi",
    "8": "Nagur",
    "9": "Salegaon",
  },
  "WOTR-v102-Shri Bhagwant Mahila-Marathi": {
    "1": "Agalgaon",
    "2": "Alipur",
    "3": "Belgaon",
    "4": "Jamgav",
    "5": "Kategaon",
    "6": "Kave",
    "7": "Khamgaon",
    "8": "Ladule",
    "9": "Mandegaon",
    "10": "Nagobachiwadi",
    "11": "Pimpalgaon",
    "12": "Ratanjan",
    "13": "Sakat",
    "14": "Sarjapur",
    "15": "Shelgaon",
    "16": "Tandulwadi",
    "17": "Umbarge",
    "18": "Undegaon",
    "19": "Vairag",
  },
  "WOTR-v102 Shri Dev Malarna-Hindi": {
    "1": "Bharoti",
    "2": "Chandnoli",
    "3": "Diwara",
    "4": "Donayacha",
    "5": "Gambheera",
    "6": "Karel",
    "7": "Khirni",
    "8": "Malarna Dungar",
    "9": "Mayapur Dungari",
    "10": "Rasoolpura",
    "11": "Shesha",
  },
  "WOTR-v102-Shri Sameswar FPC-Hindi": {
    "1": "Deo-Gaon",
    "2": "Gadaiya",
    "3": "Dangi-Khera",
    "4": "Amloda",
    "5": "Jhalara",
    "6": "Sal-Pura",
    "7": "Payra",
    "8": "Kalyana Khurd",
  },
  "WOTR-v102-Shri Yogirana Krushi-Marathi": {
    "1": "Bhotra",
    "2": "Devgav",
    "3": "Dhudhi",
    "4": "Donja",
    "5": "Gosaviwadi",
    "6": "Khasapury",
    "7": "Kokarwadi",
    "8": "Kumbhfal",
    "9": "Lakhi",
    "10": "Muggav",
    "11": "Pacpimpala",
    "12": "Pimparkhed",
    "13": "Ratnapur",
  },
  "WOTR-v102-Tuljabhavani-Marathi": {
    "1": "Ganjewadi",
    "2": "Jalkotwadi",
    "3": "Kati",
    "4": "Malimbra",
    "5": "Savargaon",
  },
  "WOTR-v102-Ujjaleswar-Odia": {
    "1": "AMBAPUR",
    "2": "ANKORADA",
    "3": "BADABURUDA",
    "4": "BADAPALLI",
    "5": "BASUDEVPUR",
    "6": "BHARAMARAPUR",
    "7": "BIRIBADIA",
    "8": "BRUNDABANAPALLI",
    "9": "CHADAYAGARDA",
    "10": "CHANABAGADA",
    "11": "GADAGOBINDAPUR",
    "12": "GANESWARPUR",
    "13": "GHODAPALANA",
    "14": "GOKARNAPUR",
    "15": "GOPALAPUR",
    "16": "GUNDURIGUDA",
    "17": "HATIBADI",
    "18": "JAGANNATHPUR",
    "19": "JAKARA",
    "20": "JAKARAPALLI",
    "21": "JANGAMA",
    "22": "JHADAPALLI",
    "23": "JHARIPADARA",
    "24": "KANDASARA",
    "25": "KARAPADA",
    "26": "KHAJURIPALLI",
    "27": "KINCIRADA",
    "28": "KOTABADAPALLI",
    "29": "KOTINADA",
    "30": "KRUSHNAKRUPAMAYEPUR",
    "31": "LADIGAON",
    "32": "LAXMINARAYANPUR",
    "33": "LOCHANAPALLI",
    "34": "MAHULAPADA",
    "35": "MALAKUTA",
    "36": "MANIKAPUR",
    "37": "MARAIBADI",
    "38": "MEGHAJHULI",
    "39": "NARASINGHAPUR",
    "40": "NARENDRAPUR",
    "41": "NUABANHAPALLI",
    "42": "NUAGAON",
    "43": "ODASINGI",
    "44": "PANDARAPADA",
    "45": "PILIKADHIA",
    "46": "RAIGUDA",
    "47": "SIDHAKHANDI",
    "48": "SIDHESWAR",
    "49": "SRIADIKANDAPUR",
    "50": "TURUBUDI",
  },
  "WOTR-v102-Umarga Shetkari Parisar-Marathi": {
    "1": "kaddora",
    "2": "Savlsur",
    "3": "Bori",
    "4": "Balsur",
    "5": "Matola",
    "6": "Madaj",
    "7": "Mulaj",
    "8": "Jakekur",
    "9": "Trikoli",
    "10": "Murum",
    "11": "Umarga",
    "12": "Kotha",
    "13": "Narangwadi",
  },
  "WOTR-v102-Uthala Mata Kisan Utpadak PC-Hindi": {
    "1": "Shambhoo Pura",
    "2": "Dhamaniya",
    "3": "Banjari",
    "4": "Bagthal",
    "5": "Roopawali",
    "6": "VALLABHNAGAR",
    "7": "Uda Khera",
    "8": "Khokharwas",
    "9": "Nawaniya",
    "10": "Jhalon Ki Bhagal",
    "11": "Naharpura",
    "12": "Menar",
    "13": "Kharsan",
    "14": "Khalator",
    "15": "Pindoliya",
    "16": "Mavli Dangiyan",
    "17": "Gadriyavas Mavli",
    "18": "Padmela",
    "19": "Satawal",
    "20": "Onarsingh Ji Ki Bhagal",
    "21": "Adinda",
    "22": "Ratarela",
    "23": "Kachher Ki Dhani",
  },
};
