const ADMIN_EMAIL = process.env.NEXT_PUBLIC_ODK_ADMIN_EMAIL;
const ADMIN_PASSWORD = process.env.NEXT_PUBLIC_ODK_ADMIN_PASSWORD;
const TEMPLATE_REST_API = process.env.NEXT_PUBLIC_TEMPLATE_REST_API;
const ATTRIBUTE_REST_API = process.env.NEXT_PUBLIC_ATTRIBUTE_REST_API;
const ODK_CENTRAL_REST_API = process.env.NEXT_PUBLIC_ODK_CENTRAL_REST_API;
const API_KEY = process.env.NEXT_PUBLIC_API_KEY;
const PIVOT_REST_API = process.env.NEXT_PUBLIC_PIVOT_REST_API;
const DOCS_URL = process.env.NEXT_PUBLIC_DOCS_URL as string;

export {
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  API_KEY,
  ATTRIBUTE_REST_API,
  DOCS_URL,
  ODK_CENTRAL_REST_API,
  PIVOT_REST_API,
  TEMPLATE_REST_API,
};
