import { faker } from "@faker-js/faker";

export const demoXmlData = {
  title: "Survey Name",
  fields: [
    {
      id: "1",
      type: "string",
      label: "What is your name?",
      required: true,
      readonly: false,
      dataAttribute: "fullName",
      hint: "fullName",
      invalid: "invalid name",
      requiredMsg: "Please enter your name",
      defaultValue: "John Doe",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "2",
      type: "int",
      label: "How old are you?",
      required: true,
      readonly: true,
      dataAttribute: "age",
      hint: "age",
      invalid: "",
      requiredMsg: "",
      defaultValue: "20",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "2.1",
      type: "int",
      label: "How old are you in slider?",
      required: true,
      readonly: false,
      dataAttribute: "ageSlider",
      hint: "ageSlider",
      invalid: "",
      requiredMsg: "ageSlider is required",
      defaultValue: "",
      appearance: "",
      style: "range",
      mediatype: "",
      sliderOptions: {
        start: "1",
        end: "10",
        step: "1",
      },
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "2.2",
      type: "int",
      label: "How old are you in vertical slider?",
      required: true,
      readonly: false,
      dataAttribute: "numericVerticalSlider",
      hint: "numericVerticalSlider",
      invalid: "",
      requiredMsg: "numericVerticalSlider is required",
      defaultValue: "",
      appearance: "vertical",
      style: "range",
      mediatype: "",
      sliderOptions: {
        start: "1",
        end: "10",
        step: "1",
      },
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "2.3",
      type: "int",
      label: "How old are you in  picker?",
      required: true,
      readonly: false,
      dataAttribute: "numericPicker",
      hint: "numericPicker",
      invalid: "",
      requiredMsg: "numericPicker is required",
      defaultValue: "",
      appearance: "picker",
      style: "range",
      mediatype: "",
      sliderOptions: {
        start: "1",
        end: "10",
        step: "1",
      },
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "2.4",
      type: "decimal",
      label: "How old are you in bearing?",
      required: true,
      readonly: false,
      dataAttribute: "numericBearing",
      hint: "numericBearing",
      invalid: "",
      requiredMsg: "numericBearing is required",
      defaultValue: "",
      appearance: "bearing",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "2.5",
      type: "decimal",
      label: "How old are you in decimal?",
      required: true,
      readonly: false,
      dataAttribute: "numericDecimal",
      hint: "numericDecimal",
      invalid: "",
      requiredMsg: "numericDecimal is required",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "3",
      type: "date",
      label: "Date",
      required: false,
      readonly: false,
      dataAttribute: "fullDate",
      hint: "fullDate",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "3.1",
      type: "date",
      label: "Year And Month Date",
      required: false,
      readonly: false,
      dataAttribute: "yearAndMonthDate",
      hint: "yearAndMonthDate",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "month-year",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "3.2",
      type: "date",
      label: "Year",
      required: false,
      readonly: false,
      dataAttribute: "year",
      hint: "year",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "year",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "3.3",
      type: "dateTime",
      label: "fullDateandTime",
      required: false,
      readonly: false,
      dataAttribute: "fullDateandTime",
      hint: "fullDateandTime",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "4",
      type: "",
      label: "Group",
      required: false,
      readonly: false,
      dataAttribute: "group1",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: true,
      groupLabel: "group1",
      groupfields: [
        {
          id: "4.1",
          type: "int",
          label: "How old are you in group 1?",
          required: false,
          readonly: false,
          dataAttribute: "ageGroup1",
          hint: "age",
          invalid: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "",
          style: "input",
          mediatype: "",
          sliderOptions: undefined,
          selectOptions: undefined,
          group: false,
          groupLabel: "",
          groupfields: [],
        },
        {
          id: "4.2",
          type: "select",
          label: "selectMutipleHorizontalLayout",
          required: false,
          readonly: false,
          dataAttribute: "selectMutipleHorizontalLayout",
          hint: "",
          invalid: "",
          requiredMsg: "",
          defaultValue: "",
          appearance: "horizontal",
          style: "select",
          selectOptions: [
            {
              label: "option1",
              value: "1",
            },
            {
              label: "option2",
              value: "2",
            },
          ],
          mediatype: "",
          sliderOptions: undefined,
          group: false,
          groupLabel: "",
          groupfields: [],
        },
      ],
    },
    {
      id: "5",
      type: "geopoint",
      label: "locationPoint",
      required: false,
      readonly: false,
      dataAttribute: "locationPoint",
      hint: "locationPoint",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "5.1",
      type: "geotrace",
      label: "locationPath",
      required: false,
      readonly: false,
      dataAttribute: "locationPath",
      hint: "locationPath",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "5.2",
      type: "geoshape",
      label: "locationShape",
      required: false,
      readonly: false,
      dataAttribute: "locationShape",
      hint: "locationShape",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "5.3",
      type: "geopoint",
      label: "locationShowMap",
      required: false,
      readonly: false,
      dataAttribute: "locationShowMap",
      hint: "locationShowMap",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "maps",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "5.4",
      type: "geopoint",
      label: "locationManual",
      required: false,
      readonly: false,
      dataAttribute: "locationManual",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "placement-map",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6",
      type: "binary",
      label: "mediaImage",
      required: false,
      readonly: false,
      dataAttribute: "mediaImage",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "upload",
      mediatype: "image/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.1",
      type: "binary",
      label: "mediaNewImage",
      required: false,
      readonly: false,
      dataAttribute: "mediaNewImage",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "new",
      style: "upload",
      mediatype: "image/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.2",
      type: "binary",
      label: "mediaSelfie",
      required: false,
      readonly: false,
      dataAttribute: "mediaSelfie",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "new-front",
      style: "upload",
      mediatype: "image/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.3",
      type: "binary",
      label: "mediaAnnotate",
      required: false,
      readonly: false,
      dataAttribute: "mediaAnnotate",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "annotate",
      style: "upload",
      mediatype: "image/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.4",
      type: "binary",
      label: "mediaDraw",
      required: false,
      readonly: false,
      dataAttribute: "mediaDraw",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "draw",
      style: "upload",
      mediatype: "image/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.5",
      type: "binary",
      label: "MediaSignature",
      required: false,
      readonly: false,
      dataAttribute: "MediaSignature",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "signature",
      style: "upload",
      mediatype: "image/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.6",
      type: "binary",
      label: "mediaAudio",
      required: false,
      readonly: false,
      dataAttribute: "mediaAudio",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "upload",
      mediatype: "audio/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.7",
      type: "binary",
      label: "mediaVideo",
      required: false,
      readonly: false,
      dataAttribute: "mediaVideo",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "upload",
      mediatype: "video/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "6.8",
      type: "binary",
      label: "MediaSelfieVideo",
      required: false,
      readonly: false,
      dataAttribute: "MediaSelfieVideo",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "new-front",
      style: "upload",
      mediatype: "video/*",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "7",
      type: "barcode",
      label: "barcode",
      required: false,
      readonly: false,
      dataAttribute: "barcode",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "input",
      mediatype: "",
      sliderOptions: undefined,
      selectOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "8",
      type: "select1",
      label: "chooseOne",
      required: false,
      readonly: false,
      dataAttribute: "chooseOne",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "select1",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "8.1",
      type: "select1",
      label: "chooseOneMinimal",
      required: false,
      readonly: false,
      dataAttribute: "chooseOneMinimal",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "minimal",
      style: "select1",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "8.2",
      type: "select1",
      label: "chooseOneTable",
      required: false,
      readonly: false,
      dataAttribute: "chooseOneTable",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "label",
      style: "select1",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "8.3",
      type: "select1",
      label: "chooseOneHorizontalLayout",
      required: false,
      readonly: false,
      dataAttribute: "chooseOneHorizontalLayout",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "horizontal",
      style: "select1",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "8.4",
      type: "select1",
      label: "chooseOneLikert",
      required: false,
      readonly: false,
      dataAttribute: "chooseOneLikert",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "likert",
      style: "select1",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "9",
      type: "select",
      label: "selectMutiple",
      required: false,
      readonly: false,
      dataAttribute: "selectMutiple",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "",
      style: "select",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "9.1",
      type: "select",
      label: "selectMutipleMinimal",
      required: false,
      readonly: false,
      dataAttribute: "selectMutipleMinimal",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "minimal",
      style: "select",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "9.2",
      type: "select",
      label: "selectMutipleTable",
      required: false,
      readonly: false,
      dataAttribute: "selectMutipleTable",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "label",
      style: "select",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
    {
      id: "9.3",
      type: "select",
      label: "selectMutipleHorizontalLayout",
      required: false,
      readonly: false,
      dataAttribute: "selectMutipleHorizontalLayout",
      hint: "",
      invalid: "",
      requiredMsg: "",
      defaultValue: "",
      appearance: "horizontal",
      style: "select",
      selectOptions: [
        {
          label: "option1",
          value: "1",
        },
        {
          label: "option2",
          value: "2",
        },
      ],
      mediatype: "",
      sliderOptions: undefined,
      group: false,
      groupLabel: "",
      groupfields: [],
    },
  ],
};

export const dashboardData = {
  title: "Development",
  description: "This is the development dashboard",
  componentTypes: [
    {
      id: "1",
      columns: "4",
      components: [
        {
          id: "1",
          type: "bar-chart",
          tag: "#barChart",
          title: "Bar Chart",
        },
        {
          id: "2",
          type: "pie-chart",
          tag: "#pieChart",
          title: "Pie Chart",
        },
        {
          id: "3",
          type: "line-chart",
          tag: "#lineChart",
          title: "Line Chart",
        },
        {
          id: "tx1372fwn",
          type: "line-chart",
          tag: "#barChart",
          title: "Line Chart",
        },
      ],
    },
    {
      id: "6r71fi4v5",
      columns: "3",
      components: [
        {
          id: "57tk3eq02",
          type: "bar-chart",
          tag: "#pieChart",
          title: "Bar Chart",
        },
        {
          id: "x8qxlf2e3",
          type: "line-chart",
          tag: "#pieChart",
          title: "Line Chart",
        },
        {
          id: "1vvamgydx",
          type: "bar-chart",
          tag: "#lineChart",
          title: "Bar Chart",
        },
      ],
    },
    {
      id: "lzsfv1c3x",
      columns: "2",
      components: [
        {
          id: "aqiwrn7b3",
          type: "pie-chart",
          tag: "#pieChart",
          title: "Pie Chart",
        },
        {
          id: "v3eq5bm9n",
          type: "map",
          tag: "#mapData2",
          title: "Map Chart",
        },
      ],
    },
    {
      id: "kfng2huww",
      columns: "1",
      components: [
        {
          id: "zw3ofxozz",
          type: "bar-chart",
          tag: "#lineChart",
          title: "Bar Chart",
        },
      ],
    },
  ],
};

const options = {
  responsive: true,
  plugins: {
    legend: {
      position: "top" as const,
    },
    title: {
      display: true,
      text: "Submission By Day",
    },
  },
};

const labels = ["January", "February", "March", "April", "May", "June", "July"];

const barData = {
  labels,
  datasets: [
    {
      label: "Dataset 1",
      data: labels.map(() => faker.number.int({ min: 10, max: 100 })),
      backgroundColor: "rgba(255, 99, 132, 0.5)",
    },
    {
      label: "Dataset 2",
      data: labels.map(() => faker.number.int({ min: 10, max: 100 })),
      backgroundColor: "rgba(53, 162, 235, 0.5)",
    },
  ],
};

const lineOptions = {
  responsive: true,
  plugins: {
    legend: {
      position: "top" as const,
    },
    title: {
      display: true,
      text: "Crop-wise Farmer Income",
    },
  },
};

const lineData = {
  labels,
  datasets: [
    {
      label: "Maize",
      data: labels.map(() => faker.number.int({ min: -1000, max: 1000 })),
      borderColor: "rgb(255, 99, 132)",
      backgroundColor: "rgba(255, 99, 132, 0.5)",
    },
    {
      label: "Wheat",
      data: labels.map(() => faker.number.int({ min: -1000, max: 1000 })),
      borderColor: "rgb(53, 162, 235)",
      backgroundColor: "rgba(53, 162, 235, 0.5)",
    },
  ],
};

const pieOptions = {
  responsive: true,
  plugins: {
    legend: {
      display: false,
      position: "left" as const,
    },
    title: {
      display: true,
      text: "Submission By Status",
    },
  },
};

const pieData = {
  labels: ["Approved", "Pending", "Rejected"],
  datasets: [
    {
      label: "# of Votes",
      data: [4, 5, 2],
      backgroundColor: [
        "rgba(255, 99, 132, 0.2)",
        "rgba(54, 162, 235, 0.2)",
        "rgba(255, 206, 86, 0.2)",
      ],
      borderColor: [
        "rgba(255, 99, 132, 1)",
        "rgba(54, 162, 235, 1)",
        "rgba(255, 206, 86, 1)",
      ],
      borderWidth: 1,
    },
  ],
};

export const tagList: any = {
  "#barChart": {
    data: barData,
    options,
  },
  "#lineChart": {
    data: lineData,
    options: lineOptions,
  },
  "#pieChart": {
    data: pieData,
    options: pieOptions,
  },
  "#totalFarmers": {
    title: "Total Farmers",
    value: faker.number.int({ min: 100, max: 1000 }),
    prefix: "",
    suffix: "",
  },
  "#card": {
    title: "Total Enumerators",
    value: 201,
    prefix: "",
    suffix: "",
  },
  "#phcCovered": {
    title: "PHCs Covered",
    value: 12,
    prefix: "",
    suffix: "31%",
  },
  "#shcCovered": {
    title: "SHCs Covered",
    value: 11,
    prefix: "",
    suffix: "15%",
  },
  "#outputBusiness": {
    title: "Output Business",
    value: 110,
    prefix: "",
    suffix: "Members",
  },
  "#totalIncome": {
    title: "Total Income",
    value: faker.number.int({ min: 100, max: 1000 }),
    prefix: "$",
    suffix: "",
  },
  "#totalCrops": {
    title: "Total Crops",
    value: faker.number.int({ min: 100, max: 1000 }),
    prefix: "",
    suffix: "",
  },
  "#totalLand": {
    title: "Total Land",
    value: faker.number.int({ min: 100, max: 1000 }),
    prefix: "",
    suffix: " acres",
  },
  "#mapData": {
    data: [
      {
        id: "AFG",
        value: 50931,
      },
      {
        id: "AGO",
        value: 366551,
      },
      {
        id: "ALB",
        value: 983642,
      },
      {
        id: "ARE",
        value: 318576,
      },
    ],
  },
  "#tableData": {
    data: [
      {
        id: 1,
        first_name: "Dorolice",
        last_name: "Gilluley",
        email: "dorolice@gmail.com",
      },
      {
        id: 2,
        first_name: "Jonathon",
        last_name: "Hartfleet",
        email: "j@gmail.com",
      },
      {
        id: 3,
        first_name: "Lynne",
        last_name: "Ferencowicz",
        email: "l@gmail.com",
      },
      {
        id: 4,
        first_name: "Cecile",
        last_name: "Bartolomeotti",
        email: "c@gmail.com",
      },
    ],
  },
  "#treeMap": {
    data: {
      name: "nivo",
      color: "hsl(353, 70%, 50%)",
      children: [
        {
          name: "viz",
          color: "hsl(307, 70%, 50%)",
          children: [
            {
              name: "stack",
              color: "hsl(123, 70%, 50%)",
              children: [
                {
                  name: "cchart",
                  color: "hsl(146, 70%, 50%)",
                  loc: 87972,
                },
                {
                  name: "xAxis",
                  color: "hsl(46, 70%, 50%)",
                  loc: 49499,
                },
                {
                  name: "yAxis",
                  color: "hsl(25, 70%, 50%)",
                  loc: 117356,
                },
                {
                  name: "layers",
                  color: "hsl(178, 70%, 50%)",
                  loc: 158464,
                },
              ],
            },
            {
              name: "ppie",
              color: "hsl(128, 70%, 50%)",
              children: [
                {
                  name: "chart",
                  color: "hsl(72, 70%, 50%)",
                  children: [
                    {
                      name: "pie",
                      color: "hsl(353, 70%, 50%)",
                      children: [
                        {
                          name: "outline",
                          color: "hsl(177, 70%, 50%)",
                          loc: 38785,
                        },
                        {
                          name: "slices",
                          color: "hsl(265, 70%, 50%)",
                          loc: 37685,
                        },
                        {
                          name: "bbox",
                          color: "hsl(162, 70%, 50%)",
                          loc: 114397,
                        },
                      ],
                    },
                    {
                      name: "donut",
                      color: "hsl(196, 70%, 50%)",
                      loc: 59393,
                    },
                    {
                      name: "gauge",
                      color: "hsl(31, 70%, 50%)",
                      loc: 98623,
                    },
                  ],
                },
                {
                  name: "legends",
                  color: "hsl(100, 70%, 50%)",
                  loc: 88258,
                },
              ],
            },
          ],
        },
        {
          name: "colors",
          color: "hsl(318, 70%, 50%)",
          children: [
            {
              name: "rgb",
              color: "hsl(4, 70%, 50%)",
              loc: 20518,
            },
            {
              name: "hsl",
              color: "hsl(147, 70%, 50%)",
              loc: 181444,
            },
          ],
        },
      ],
    },
  },
  "#heatMap": {
    data: [
      {
        id: "Japan",
        data: [
          {
            x: "Train",
            y: -52251,
          },
          {
            x: "Subway",
            y: -13724,
          },
          {
            x: "Bus",
            y: -58992,
          },
          {
            x: "Car",
            y: -75832,
          },
          {
            x: "Boat",
            y: 75145,
          },
          {
            x: "Moto",
            y: 6554,
          },
          {
            x: "Moped",
            y: -17888,
          },
          {
            x: "Bicycle",
            y: -22908,
          },
          {
            x: "Others",
            y: -43762,
          },
        ],
      },
      {
        id: "France",
        data: [
          {
            x: "Train",
            y: 53445,
          },
          {
            x: "Subway",
            y: -78645,
          },
          {
            x: "Bus",
            y: 67358,
          },
          {
            x: "Car",
            y: 7292,
          },
          {
            x: "Boat",
            y: -32401,
          },
          {
            x: "Moto",
            y: 16767,
          },
          {
            x: "Moped",
            y: -1848,
          },
          {
            x: "Bicycle",
            y: -42918,
          },
          {
            x: "Others",
            y: -19821,
          },
        ],
      },
    ],
  },
  "#mapData2": {
    data: [
      {
        id: "ARE",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "ARG",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "ARM",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "ATA",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "ATF",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "AUT",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "AZE",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BDI",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BEL",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BEN",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BFA",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BGD",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BGR",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BHS",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BIH",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BLR",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BLZ",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BOL",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BRN",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BTN",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "BWA",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CAF",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CAN",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CHE",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CHL",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CHN",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CIV",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "CMR",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "COD",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "COG",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
      {
        id: "COL",
        value: faker.number.int({ min: 10000, max: 1000000 }),
      },
    ],
  },
};



export const getDataFromTag = (tag: any) => {
  return tagList[tag];
};
